# Main task configuration for configurable pick and place

task:
  name: "configurable_pick_drop"
  sequence_mode: "sequential"
  
# List of objects to include in the task (references objects_config.yaml)
objects:

  - name: "rtx_3080"  # This will be the key used to lookup in objects_config.yaml
    enabled: true
    priority: 1  # Lower numbers processed first in sequential mode
    n_rows: 2
    n_col: 2
    target_n_rows: 2
    target_n_col: 2
    n_layers: 1
    pick_r_space: 0.18
    pick_c_space: 0.08
    target_r_space: 0.18
    target_c_space: 0.08
    target_l_space: 0.03

  - name: "blue_cube"
    enabled: false
    priority: 1
  
  - name: "green_cube" 
    enabled: false
    priority: 3



robot:
  type: "franka"
  end_effector_height: 0.5
  gripper_offset: [0, 0.005, 0]

mobile_robot:
  position: [0.3, -0.5, 0]

environment:
  include_pallet: false
  pallet_position: [-5, -5, 0]
  pallet_scale: [0.9, 0.9, 0.9]
